name: artefact
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - traffic=2.8.1
  - mlflow
  - tqdm
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pyarrow
  # - google-cloud-storage
  - wandb
  - plotly
  - pip
  - pip:
      - "poetry>=1.5.1"
